URLS = [
    "url1"
]
STATUSPAGE_API_KEY = ""
STATUSPAGE_PAGE_ID = ""
STATUSPAGE_METRICS = {
    "url": "metric_id"
}
STATUSPAGE_COMPONENTS = {
    "url": "component_id"
}
PING_WEBHOOKS = []
STATUS_WEBHOOKS = []
ESCALATION_IDS = []
POLL_TIME = 60
OUTAGE_CHANGE_AFTER = 10
DRY_MODE = False
DEGRADED_PERFORMANCE_TARGET_PING = 500
TIMEOUT_PING = 30000
